# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-10 21:08
from __future__ import unicode_literals

import common.mixins
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import search.mixins
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailimages', '0021_image_file_hash'),
        ('common', '0047_externalcontrollerconfig_allows_wct'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilerplateAboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heading', models.CharField(default='', max_length=255)),
                ('sub_heading', wagtail.core.fields.RichTextField()),
                ('body', wagtail.core.fields.RichTextField()),
                ('cta_heading', models.CharField(default='', max_length=255)),
                ('cta_sub_heading', models.CharField(default='', max_length=255)),
                ('cta_text', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(common.mixins.DynamicPhoneNumberMixin, search.mixins.ShortformModalMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='BoilerplateBlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('sub_title', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(common.mixins.DynamicPhoneNumberMixin, search.mixins.ShortformModalMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='BoilerplateBlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField()),
                ('date', models.DateField(verbose_name='Post date')),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='common.BlogCategory')),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(common.mixins.DynamicPhoneNumberMixin, search.mixins.ShortformModalMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='BoilerplateBlogPageRelatedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='boilerplate.BoilerplateBlogPage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BoilerplateBlogPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='boilerplate.BoilerplateBlogPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boilerplate_boilerplateblogpagetag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoilerplateContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(common.mixins.DynamicPhoneNumberMixin, search.mixins.ShortformModalMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='BoilerplateIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BoilerplateLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('sub_title', models.CharField(default='', max_length=255)),
                ('body', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(common.mixins.DynamicPhoneNumberMixin, search.mixins.ShortformModalMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='BoilerplatePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(common.mixins.DynamicPhoneNumberMixin, search.mixins.ShortformModalMixin, 'wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='boilerplateblogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='boilerplate.BoilerplateBlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
